import fs from "node:fs";
import path from "node:path";
import type { AgentConfig } from "../types/config.js";
import { resolveTemplatePath } from "./templateRegistry.js";

export function scaffoldProject(config: AgentConfig) {
  validateProjectName(config.projectName);

  const projectPath = path.join(process.cwd(), config.projectName);
  const templatePath = resolveTemplatePath(config.architecture);

  if (fs.existsSync(projectPath)) {
    throw new Error(`Destination already exists: ${config.projectName}`);
  }

  fs.mkdirSync(projectPath, { recursive: true });
  copyDirectory(templatePath, projectPath);

  writeProjectFiles(projectPath, config);
}

function writeProjectFiles(projectPath: string, config: AgentConfig) {
  const packageJson = {
    name: config.projectName,
    version: "0.1.0",
    private: true,
    type: "module",
    scripts: {
      dev: "tsx src/index.ts",
    },
    dependencies: {},
    devDependencies: {
      tsx: "^4.19.0",
      typescript: "^5.6.0",
    },
  };

  fs.writeFileSync(
    path.join(projectPath, "package.json"),
    JSON.stringify(packageJson, null, 2) + "\n"
  );

  const readme = `# ${config.projectName}\n\nThis project was generated by create-agent-app.\n\n## Getting started\n\nRun the development server:\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`;

  fs.writeFileSync(path.join(projectPath, "README.md"), readme);

  const agentConfig = `provider: ${config.provider}\narchitecture: ${config.architecture}\n`;

  fs.writeFileSync(path.join(projectPath, ".agentrc"), agentConfig);
}

function copyDirectory(source: string, target: string) {
  for (const entry of fs.readdirSync(source, { withFileTypes: true })) {
    const srcPath = path.join(source, entry.name);
    const destPath = path.join(target, entry.name);

    if (entry.isDirectory()) {
      fs.mkdirSync(destPath, { recursive: true });
      copyDirectory(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

function validateProjectName(projectName: string) {
  if (!projectName.trim()) {
    throw new Error("Project name cannot be empty");
  }

  if (!/^[a-z0-9-]+$/i.test(projectName)) {
    throw new Error("Project name can only contain letters, numbers, and dashes");
  }
}
